### ISSUE TITLE
Validation Role: Tools of the Trade

### ISSUE THREAD

**Issue by RAytoun** [hotosm/ActivationCurriculum#88]
https://hotosm.gitbook.io/curriculumworkspace/validation-role/tools-of-the-trade
Because the link to the LearnOSM Tasking Manager may open in the TM3 version please add the text that is in italics to the instructions in the course... 
**Items to Read**
**LearnOSM: Tasking Manager**

Hopefully you've seen the LearnOSM module dedicated to the Tasking Manager by now, please make a quick review; or take some time to go through it if it's your first time. _Remember to click on the green **our version overview** and select the Tasking Manager 4 version._

**Comment by russdeffner** [comment]
Fixed in https://github.com/hotosm/ActivationCurriculum/commit/6282aab0376df2455675f239a4588ad1fe304314
